import type { Store } from "@srvm/core";
import type pg from "pg";
import {
  resolveConnection,
  resolveTable,
  quoteIdentifier,
  openDatabase,
  query,
  rows,
  rowCount,
  transaction,
  scriptName,
  scriptChecksum,
} from "./utils.js";

export type PostgresStoreOptions = {
  adapter?: "postgres";
  connection?: string;
  scriptMigrationTable?: string;
};

export function defineStore(options: PostgresStoreOptions = {}): Store {
  if (options.adapter !== undefined && options.adapter !== "postgres") {
    throw new Error(`Unsupported adapter "${options.adapter}"`);
  }

  return createStore(options);
}

export function createStore(options: PostgresStoreOptions = {}): Store {
  const connection = resolveConnection(options.connection);
  const scriptMigrationTable = resolveTable(options.scriptMigrationTable);
  const table = quoteIdentifier(scriptMigrationTable);

  let database: pg.Pool | undefined;
  let chain: Promise<void> = Promise.resolve();

  function enqueue<T>(task: () => Promise<T>): Promise<T> {
    const result = chain.then(task);
    chain = result.then(
      () => undefined,
      () => undefined,
    );
    return result;
  }

  async function getDb(): Promise<pg.Pool> {
    if (database) {
      return database;
    }

    database = await openDatabase(connection);
    return database;
  }

  return {
    adapter: "postgres",
    connection,
    scriptMigrationTable,

    setup() {
      return enqueue(async () => {
        const db = await getDb();
        await query(
          db,
          `CREATE TABLE IF NOT EXISTS ${table} (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            step INTEGER NOT NULL UNIQUE,
            script TEXT NOT NULL UNIQUE,
            script_checksum TEXT NOT NULL,
            applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
          )`,
        );
      });
    },

    getApplied() {
      return enqueue(async () => {
        const db = await getDb();
        const result = await query<{ step: number; script: string }>(
          db,
          `SELECT step, script FROM ${table} ORDER BY step ASC`,
        );
        return rows(result).map((row) => ({
          step: Number(row.step),
          script: row.script,
        }));
      });
    },

    execute(script) {
      return enqueue(async () => {
        const db = await getDb();
        const name = scriptName(script);
        const checksum = scriptChecksum(script);

        const alreadyApplied = await transaction(db, async (client) => {
          const existing = await one<{ script_checksum: string }>(
            client,
            `SELECT script_checksum FROM ${table} WHERE script = $1`,
            [name],
          );

          if (!existing) {
            return false;
          }

          if (existing.script_checksum !== checksum) {
            throw new Error(
              `Checksum mismatch for applied script "${name}". The script changed after it was recorded.`,
            );
          }

          return true;
        });

        if (alreadyApplied) {
          return false;
        }

        await script.up();

        await query(
          db,
          `INSERT INTO ${table} (step, script, script_checksum)
           VALUES ((SELECT COALESCE(MAX(step), 0) + 1 FROM ${table}), $1, $2)`,
          [name, checksum],
        );
        return true;
      });
    },

    rollback(script) {
      return enqueue(async () => {
        const db = await getDb();
        const name = scriptName(script);
        const existing = await one<{ script: string }>(
          db,
          `SELECT script FROM ${table} WHERE script = $1`,
          [name],
        );
        if (!existing) {
          return;
        }

        await script.down();
        const result = await query(db, `DELETE FROM ${table} WHERE script = $1`, [name]);
        if (rowCount(result) === 0) {
          throw new Error(`Script "${name}" is not applied`);
        }
      });
    },

    rollbackAll() {
      return enqueue(async () => {
        const db = await getDb();
        await query(db, `DELETE FROM ${table}`);
      });
    },

    rollbackTo(step) {
      return enqueue(async () => {
        if (!Number.isInteger(step) || step < 0) {
          throw new Error(`Rollback step must be a non-negative integer, received ${String(step)}`);
        }

        const db = await getDb();
        await query(db, `DELETE FROM ${table} WHERE step > $1`, [step]);
      });
    },

    rollbackToLast() {
      return enqueue(async () => {
        const db = await getDb();
        const removed = await transaction(db, async (client) => {
          const latest = await one<{ step: number | null }>(client, `SELECT MAX(step) AS step FROM ${table}`);
          if (latest?.step == null) {
            return false;
          }

          await query(client, `DELETE FROM ${table} WHERE step = $1`, [latest.step]);
          return true;
        });

        if (!removed) {
          throw new Error("No applied scripts to roll back");
        }
      });
    },
  };
}

function one<T extends pg.QueryResultRow>(
  db: pg.Pool | pg.PoolClient,
  sql: string,
  params: unknown[] = [],
): Promise<T | undefined> {
  return query<T>(db, sql, params).then((result) => rows(result)[0]);
}
