import pg from "pg";
import { defineScript } from "@srvm/core";

export default defineScript({
  meta: {
    name: "Create notes",
    description: "Creates the notes table",
  },
  async up() {
    const client = new pg.Client({ connectionString: process.env.DATABASE_URL });
    await client.connect();
    try {
      await client.query(`
        CREATE TABLE IF NOT EXISTS notes (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          body TEXT NOT NULL
        )
      `);
      console.log("created notes");
    } finally {
      await client.end();
    }
  },
  async down() {
    const client = new pg.Client({ connectionString: process.env.DATABASE_URL });
    await client.connect();
    try {
      await client.query("DROP TABLE IF EXISTS notes");
      console.log("dropped notes");
    } finally {
      await client.end();
    }
  },
});
